{% set name = "quilt" %}
{% set pname = "quilt3" %}
{% set version = "6.3.1" %}

package:
  name: {{ pname|lower }}
  version: {{ version }}

source:
  url: https://github.com/quiltdata/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 50878c9a76c6e3a2306b4e995fbaa1bf667642cbf601e6377090125dd3daaae0

build:
  number: 0
  skip: true  # [py<39]
  script:
    - cd api/python
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  entry_points:
    - quilt3=quilt3.main:main

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - boto3 >=1.21.7
    - jsonschema >=3,<5
    - jsonlines ==1.2.0
    - platformdirs >=2
    - pydantic >=2.0.0,<3.0.0
    - pyyaml >=5.1
    - requests >=2.12.4
    - requests-futures ==1.0.0
    - tenacity >=5.1.1,!=8.4.0
    - tqdm >=4.32
  run_constrained:
    - anndata >=0.8.0 # extra:anndata
    - quilt3_local >=2,<3 # extra:catalog
    - uvicorn >=0.15,<0.18 # extra:catalog
    # pip install --dry-run "aiobotocore[boto3]>=2" will take only boto3 >=1.37.0,<1.37.2,
    # The conda dependency solver will decide which version to take instead of the upstream extras versions.
    #- aiobotocore >=2 # extra:catalog
    - numpy >=1.14.0 # extra:pyarrow
    - pandas >=0.19.2 # extra:pyarrow
    - pyarrow >=0.14.1 # extra:pyarrow

test:
  imports:
    - quilt3
  source_files:
    - api/python/tests
  requires:
    - pip
    - pytest
    - pytest-subtests
    - numpy >=1.14.0 # extra:pyarrow
    - pandas >=0.19.2 # extra:pyarrow
    - pyarrow >=0.14.1 # extra:pyarrow
    - responses
  commands:
    - pip check
    - cd api/python
    # FAILED tests/integration/test_packages.py::PackageTest::test_manifest - locale.Error: unsupported locale setting
    - export LC_ALL=en_US.UTF-8  # [osx]
    # No the anndata package available on the main channel
    # Skip test_get_boto3_session because of requests.exceptions.MissingSchema: Invalid URL 'None/api/auth/get_credentials': No scheme supplied. 
    - pytest tests -vv --ignore=tests/test_formats.py -k "not test_get_boto3_session"

about:
  home: https://www.quilt.bio/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Quilt: where data comes together'
  description: |
    Quilt connects teams to actionable data by simplifying data discovery, sharing, and analysis.
    It's designed to serve data-driven organizations with powerful tools for managing data as code,
    enabling rapid experimentation, and ensuring data integrity at scale.
  dev_url: https://github.com/quiltdata/quilt
  doc_url: https://docs.quilt.bio/

extra:
  recipe-maintainers:
    - knaaptime
    - akarve
